### ISSUE TITLE
real_images and label 

### ISSUE THREAD

**Issue by Zonobia-A** [rosinality/sagan-pytorch#3]
Hello,i have not solve the problem yesterday, because i dont know why i use one dataset without label, sample_data function can also get  label from dataset.

**Comment by rosinality** [comment]
ImageFolder dataset class automatically assigns label to images by using directory structure (that is, directory that contains that image.) For example:

Root
- A
  - ImageA.png
- B
  - ImageB.png

Then, ImageA.png will be class A and ImageB.png will be class B.

**Comment by rosinality** [comment]
No. 'A' directory contains images that belongs to class A and 'B' directory contanins images that belongs to class B. Then ImageFolder reads all images in these directories and automatically assigns label to images by using these directory structure. That is, images in 'A' directory would be class A and images in 'B' directory would be class B.

**Comment by Zonobia-A** [comment]
Thank you very much!
