### ISSUE TITLE
discriminator doesn't use self attention

### ISSUE THREAD

**Issue by rjeli** [rosinality/sagan-pytorch#5]
https://github.com/rosinality/sagan-pytorch/blob/39ec21b87d77550149c28fda76fc74d9db5e7ad9/model.py#L202

self-attention isn't passed, intentional?

**Comment by rosinality** [comment]
It's my mistake. Corrected it. Sorry.

**Comment by rjeli** [comment]
☺️ thanks for the repo, it helps a lot!
