### ISSUE TITLE
FID scores in README.

### ISSUE THREAD

**Issue by Gsunshine** [rosinality/sagan-pytorch#7]
I read the code fid.py and found that it calculates intra FID rather than FID. 
Thus I doubt whether the FID scores reported in README is actually intra FID. 

Hope you can reply at your convenience. Thx!

**Comment by rosinality** [comment]
I think it is the mean of intra FIDs.

**Comment by Gsunshine** [comment]
> I think it is the mean of intra FIDs.

Thx!
However, I check the original results of intra FID in the paper, finding 83.7 reported which is much higher than one GPU version Res-SAGAN in README (64.8). 

I am fairly confused. Guess it could be FID rather than intra FID? 
It has been 2 years since this repo got released. Thx for your reply!

**Comment by rosinality** [comment]
This implementation is quite different from official implementation as I made this before official implementation came out, and I didn't experimented on full imagenet. (only on 10 classes)

Also, using pytorch inception model for calculating FIDs is not very appropriate - it will report FIDs lower than when using tensorflow inception. You will need to use like this https://github.com/mseitzer/pytorch-fid if you want to calculate FID in pytorch.

**Comment by Gsunshine** [comment]
> This implementation is quite different from official implementation as I made this before official implementation came out, and I didn't experimented on full imagenet. (only on 10 classes)
> 
> Also, using pytorch inception model for calculating FIDs is not very appropriate - it will report FIDs lower than when using tensorflow inception. You will need to use like this https://github.com/mseitzer/pytorch-fid if you want to calculate FID in pytorch.

Thx!
I think the implementation of self attention itself is right though the entire net is different. At least it is OK for a light, fast and fair experiment with only one GPU : ).

I conduct a simple comparison using DC-SAGAN in this repo's model.py as a baseline. FID of  DC-SAGAN is approximately 85 while intra FID is 222 (All 1000 classes in ImageNet 128*128, 1500K & ~3 weeks, TTUR 1:5, batch size 64). This result is enough for a fair comparison since simple baseline may enlarge the performance gap to make more significant differences.

FID & intra FID reported above has been rewrited to ensure it is comparable with other results using original InceptionV3 in pytorch. You may add this result to README if it is helpful.

I will futher conduct formal comparisons in tf, which might be much heavier : ). Thx for your help.
